### ISSUE TITLE
Reporter throws error

### ISSUE THREAD

**Issue by marceljay** [ItsNickBarry/hardhat-storage-layout-diff#1]
The tool seems like a nicer interface than interacting directly with `solc` but as I've tried it, an error was thrown:

```
└─$ yarn run hardhat export-storage-layout                                                                                                        1 ⚙
yarn run v1.22.10
$ /home/code/packages/hardhat/node_modules/.bin/hardhat export-storage-layout
An unexpected error occurred:

Error: Cannot find module 'simple-git'
Require stack:
- /home/code/packages/hardhat/node_modules/hardhat-storage-layout-diff/index.js
- /home/code/packages/hardhat/hardhat.config.ts
- /home/code/packages/hardhat/node_modules/hardhat/internal/core/config/config-loading.js
- /home/code/packages/hardhat/node_modules/hardhat/internal/cli/cli.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._resolveFilename.sharedData.moduleResolveFilenameHook.installedValue [as _resolveFilename] (/home/code/packages/hardhat/node_modules/@cspotcode/source-map-support/source-map-support.js:679:30)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/home/code/packages/hardhat/node_modules/hardhat-storage-layout-diff/index.js:4:19)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/code/packages/hardhat/node_modules/hardhat-storage-layout-diff/index.js',
    '/home/code/packages/hardhat/hardhat.config.ts',
    '/home/code/packages/hardhat/node_modules/hardhat/internal/core/config/config-loading.js',
    '/home/code/packages/hardhat/node_modules/hardhat/internal/cli/cli.js'
  ]
}
error Command failed with exit code 1.
```

Is the project still maintained?

**Comment by ItsNickBarry** [comment]
Fixed in version `0.0.4`.  This project is experimental, and not a priority at the moment, but I will take a look at any issues reported as availability permits.
